### ISSUE TITLE
DHCP Snooping ähnlichers veralten auf den LAN-Ports

### ISSUE THREAD

**Issue by bitnukl** [VfN-NRW/gluon-firmware-builder#103]
Wenn wir LAN-Ports abschalten, wenn sie einen DHCP-Server erkenne, könnten wir falsch angeklemmte private Router erkennen und ein doppeltes DHCP verhindern.

**Comment by RubenKelevra** [comment]
Vorschlag ist in https://github.com/VfN-NRW/gluon-firmware-builder/issues/106 aufgegangen.
