### ISSUE TITLE
br-client does not exist on x86 image (on Futro Hardware)

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#11]
_From @RubenKelevra on July 3, 2016 18:27_

The bridge seems to be not configured right, which leads to a constant reboot, because there is no working mesh communications.

_Copied from original issue: VfN-NRW/gluon#108_

**Comment by RubenKelevra** [comment]
hopefully fixed with
fe33fdd2f37b23bc324bdcb20bbcaf6f4088ed42
c56e9bac9143e3353b59d4773b1ce698263efd02
711560e916ef648210a05465cfbb8c3a6c91928f
35ad709b2e6cf6d8e02d60d2e703ced0fb8cedd8

**Comment by bitnukl** [comment]
Fehler ist behoben
