### ISSUE TITLE
Den DNS-Server in den Nodes auf Herz und Nieren testen, der auf der...

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#115]
... next-hop IP liegt.

Abhängig von:
https://github.com/VfN-NRW/gluon-firmware-builder/issues/114

Danach können wir auf den Gateways per Radvd die Next-Hop-IP als DNS ausliefern und dezentrales DNS-Caching betreiben.

**Comment by bitnukl** [comment]
Ist das wirklich etwas für die Beta? Oder doch eher 4.2.1

**Comment by RubenKelevra** [comment]
schaut gut aus. :)
