### ISSUE TITLE
Delay-File beim boot generieren für */5-Minuten Scripte

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#116]
Das sorgt dafür, dass sich die Netzwerk-Belastung gleichmäßig zeitlich gesehen verteilt.

**Comment by bitnukl** [comment]
Was soll da genau passieren mit den Skripten?

**Comment by RubenKelevra** [comment]
Man müsste ne Nummer generieren und in /tmp ablegen, 0-300

Dann müsste man bei allen */5 scripten ein 

```
delay="$(cat /tmp/delayfile)"
sleep "${delayfile:-1}"
```

machen

**Comment by bitnukl** [comment]
also:
**echo $[( $RANDOM % 299 )] > /tmp/randomdelay**
(wohin auch immer ein guter Ort für Autostart ist)
und in die Skripte:
**sleep $(cat /tmp/randomdelay)**

**Comment by RubenKelevra** [comment]
Unbedingt mit einem Default-Wert aufrufen, sonst crasht der Aufruf wegen fehlendem Parameter. :)
