### ISSUE TITLE
Alle Updates manuell testen

### ISSUE THREAD

**Issue by bitnukl** [VfN-NRW/gluon-firmware-builder#125]

**Comment by bitnukl** [comment]
Tests 740N @ 6.6
mesh ok
update ok
config mode ok
**mac NICHT OK** 
f81a677228cd => 
f81a677228ce

Tests 740N @ 6.9
mesh ok
update ok
config mode ok
**mac NICHT OK** 
f81a677228cd => 
f81a677228ce

**Comment by RubenKelevra** [comment]
Wir müssen unbedingt die UniFis testen

Sowohl mit als auch ohne großem HostAPd

**Comment by bitnukl** [comment]
740N, 841N, AP_AC_Pro getestet.
Updates von 0.6.6, 0.6.9, 0.8.0pre und 4.2a funktionieren.
Mit und ohne LAN-WAN-Bridge.

**Comment by RubenKelevra** [comment]
Reicht mir für n kleinen Lauf in Lindlar. :)
