### ISSUE TITLE
IGMP snooping wieder deaktivieren

### ISSUE THREAD

**Issue by bitnukl** [VfN-NRW/gluon-firmware-builder#126]

**Comment by RubenKelevra** [comment]
fixed

**Comment by kevin-olbrich** [comment]
Warum hast du dich dafür entschieden?

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

## 

Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
Bevor wir das an machen müssen wir andere Dinge implementieren, die nicht mehr in den Milestone passen. 

Wird wieder an gemacht :)
https://github.com/VfN-NRW/gluon-firmware-builder/issues/127
