### ISSUE TITLE
 [Security flaw] Prüfen ob wir betroffen sind

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#133]
https://sekurak.pl/tp-link-httptftp-backdoor/

https://sekurak.pl/more-information-about-tp-link-backdoor/

**Comment by kaechele** [comment]
Dieser bug bedingt das Vorhandensein der originalen Firmware

**Comment by RubenKelevra** [comment]
Okay, beim Überfliegen klang es so, als sei das ein Bug im TFTP vom Bootloader
