### ISSUE TITLE
[Backend]: Aus einem Stats-Transfer eine Transaktion erstellen

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#138]
Derzeit ist jedes Update/Insert ein eigener Commit, die Festplatte raucht. Daher wäre eine Transaktion für ein komplettes Stats-Update hilfreich.

**Comment by kevin-olbrich** [comment]
Sind die Stats alle in einem request oder in mehreren? Ersteres wäre sehr einfach zu lösen.

Mit freundlichen Grüßen / best regards,
Kevin Olbrich.

(mobil vom iPhone)

--
Diese E-Mail enthält vertrauliche und/oder rechtlich geschützte Informationen. Wenn Sie nicht der richtige Adressat sind und/oder diese E-Mail irrtümlich erhalten haben, informieren Sie bitte sofort den Absender und vernichten Sie diese Mail. Das unerlaubte Kopieren sowie die unbefugte Weitergabe dieser Mail ist nicht gestattet.

**Comment by RubenKelevra** [comment]
Ein Transfer. Bei dem Backend ist derzeit nichts "einfach". ;)

**Comment by kevin-olbrich** [comment]
Dann stelle ich Django als potentielle Lösung mal in den Raum.

**Comment by RubenKelevra** [comment]
Nein.

Hier gehts um keine Neuimplementierung, sondern eine Optimierung des bestehenden - siehe Tags.
