### ISSUE TITLE
[Stats] Stepback implementieren: Wenn Curl mit einem Fehler zurück kommt (nicht Timeout) 60 Sekunden warten

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#139]
Denn es könnte gut sein, dass nur die Verbindung abgebrochen ist. Würden wir direkt neu übertragen würden beide Transaktionen im SQL-Server einen Konflikt verursachen. Das könnte einen Stall auslösen für diesen Node, dass dieser überhaupt keine Stats mehr übertragen bekommt.

**Comment by bitnukl** [comment]
not a problem
