### ISSUE TITLE
5 GHz Channel überdenken

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#140]
@bitnukl schaut so als wäre Channel 108 ne blöde Wahl:
![17120616](https://cloud.githubusercontent.com/assets/614929/17435702/c985149c-5b12-11e6-9f14-9678d6ebea66.png)

**Comment by bitnukl** [comment]
Wenn 80er Kanäle willst, können wir auch auf 100 gehen, 108 und 112 ist nur am wenigsten los.
Wenn du 40 Kanäle machst sind da am wenigsten WLANs, kein Radar und keine 5GHz Videobrücken und so etwas.

**Comment by RubenKelevra** [comment]
Die Geräte machen wenn sie können VHT80, entsprechend wäre wohl 100 besser. Wenn das Wetterradar vorbei kommt könnte es sonst sein dass 5 GHz ausfällt. Weiß nicht ob der Treiber das kann mit auf 40 MHz limitieren ...

**Comment by RubenKelevra** [comment]
In jedem Fall sollten wir den Kanal benutzen der einen zweiten VHT80 daneben zulässt :)

**Comment by bitnukl** [comment]
done!
Wir sind auf Kanal 100
