### ISSUE TITLE
Wenn an WAN kein DHCP anliegt, geht der Knoten auch über Mesh nicht online

### ISSUE THREAD

**Issue by bitnukl** [VfN-NRW/gluon-firmware-builder#154]
offline SSID bis man das Kabel zieht.
Müssten wir mal testen ob das beim Installieren mit neuster Firmware immer noch passiert.

**Comment by RubenKelevra** [comment]
wie verlaufen eure Tests so @bitnukl und @grmp ?

**Comment by grmp** [comment]
Noch nichts geschafft. Test-Hardware noch nicht bereit, war die letzten Tage "nicht im Lande".
Sobald ich die Hardware habe (und mal zu Hause bin) teste ich. :-)
