### ISSUE TITLE
Updatewahrscheinlichkeit für "rc" anpassen?

### ISSUE THREAD

**Issue by bitnukl** [VfN-NRW/gluon-firmware-builder#156]
Da das eh kaum ein "normaler Nutzer" aktiviert, können wir das Updateverhalten für Testknoten auf 2-3 Tage heruntersetzen anstelle von zwei Wochen. Kommentare?

**Comment by RubenKelevra** [comment]
Hm klar, können wir machen. :)

**Comment by bitnukl** [comment]
https://github.com/VfN-NRW/gluon-firmware-builder/commit/cdb5928cfb4deb7d7e4e91eff383fb5d816f8c54 ändert die  Updatewahrscheinlichkeit für "rc" auf 33%
