### ISSUE TITLE
Offline-SSID verhindert Verbindung, wenn 5 GHz deaktiviert.

### ISSUE THREAD

**Issue by zawhie** [VfN-NRW/gluon-firmware-builder#170]
**Firmware:** gluon-remscheid-4.2.0-tp-link-archer-c7-v2.bin
**Access-Point:** TP-Link Archer C7v2

**Problem:** Sobald das Freifunk auf 5 GHz deaktiviert wird, verlieren die Clients auf 2,4 GHz die Verbindung, unabhängig, ob diese mit Freifunk oder dem privaten WLAN (5 GHz) verbunden sind. Wird Freifunk auf 5 GHz wieder aktiviert läuft alles ohne Probleme.

(Freifunk 2,4 GHz: an, Freifunk 5 GHz: aus, Private 2,4 GHz: aus, Private 5 GHz: an => Verbindung wird verloren
Freifunk 2,4 GHz: an, Freifunk 5 GHz: an, Private 2,4 GHz: aus, Private 5 GHz: an => Stabil)
Ausgabe von iwinfo und logread im Fehlerfall: https://nopaste.me/view/49500607#L27

**work-around:** Nachdem das Skript _offline-ssid_ aus /usr/lib/micrond entfernt wurde bleibt die Verbindung stabil, auch wenn Freifunk auf 5GHz deaktiviert wurde.
(Freifunk 2,4 GHz: an, Freifunk 5 GHz: aus, Private 2,4 GHz: aus, Private 5 GHz: an, _offline-ssid_ => stabil)

**Comment by RubenKelevra** [comment]
duplicate of this bug: https://github.com/VfN-NRW/gluon-firmware-builder/issues/166
