### ISSUE TITLE
Gluon-Version stimmt nicht bei 0.8

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#26]
_From @RubenKelevra on November 17, 2015 15:29_

Gluon-Version
v2014.4-1230-g910d144
Firmware-Release
0.8.0~prebeta5

_Copied from original issue: VfN-NRW/gluon#81_

**Comment by RubenKelevra** [comment]
need to reconfirm this bug on latest version (0.8.1~alpha1)

**Comment by bitnukl** [comment]
fixed
