### ISSUE TITLE
Add patches which increases roaming behavior for broken devices

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#44]
For Multicast-Applications 

https://github.com/freifunk-gluon/gluon/commit/4d00c804c0988bc957580b6813fcd283dbb0d6fd

**Comment by bitnukl** [comment]
patch added: https://github.com/VfN-NRW/gluon-firmware-builder/commit/0895c3d12b6f7fbf67087e79b845fddb79f4591e
