### ISSUE TITLE
ist elp_interval = 500 nicht viel zu niedrig?

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#57]
https://www.open-mesh.org/projects/batman-adv/wiki/Tweaking

**Comment by bitnukl** [comment]
warum zu niedrig? 2 Pakete die Sekunde auf dem lokalen Link ist doch nicht zu viel.

**Comment by RubenKelevra** [comment]
Kommt drauf an wieviele Neighbors es gibt, wenn da 10 Router in Reichweite stehen, sind es 200 Pakete die Sekunde ...

**Comment by bitnukl** [comment]
denke das schieben wir...
