### ISSUE TITLE
Konfig mode startet nicht, LUA Fehlermelung 

### ISSUE THREAD

**Issue by bitnukl** [VfN-NRW/gluon-firmware-builder#6]
/usr/lib/lua/luci/dispatcher.lua:364: Failed to execute function dispatcher target for entry '/'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:364: Failed to execute function dispatcher target for entry '/gluon-config-mode'.
The called action terminated with an exception:
/usr/lib/lua/luci/dispatcher.lua:364: Failed to execute cbi dispatcher target for entry '/gluon-config-mode/wizard'.
The called action terminated with an exception:
.../lib/lua/luci/model/cbi/gluon-config-mode/wizard.lua:18: wrong number of arguments to 'insert'
stack traceback:
    [C]: in function 'assert'
    /usr/lib/lua/luci/dispatcher.lua:364: in function 'dispatch'
    /usr/lib/lua/luci/dispatcher.lua:135: in function </usr/lib/lua/luci/dispatcher.lua:134>

**Comment by RubenKelevra** [comment]
Frage ob das in der letzten Version auch noch auftritt.

**Comment by bitnukl** [comment]
Jap, jetzt auch auf v11

**Comment by RubenKelevra** [comment]
Wir haben gestern vermutet das dieser Commit läuft: https://github.com/VfN-NRW/gluon-firmware-builder/commit/3ab4006328a9bacabbd12565bb17aa1b881252d5 

Nein tut er nicht.

**Comment by RubenKelevra** [comment]
Ich hab https://github.com/VfN-NRW/gluon-firmware-builder/commit/d5e036c29bdec9bf741925ba3ceddf4690491e96 probiert, das funktioniert.

**Comment by RubenKelevra** [comment]
Ich hab https://github.com/VfN-NRW/gluon-firmware-builder/commit/8a52ccb5938f280f1ab79f047eac3ed61df7dc96 probiert, funktioniert auch.

**Comment by RubenKelevra** [comment]
```
eb879ca9e890e4248353fa0220555ee02c810d85 is the first bad commit
commit eb879ca9e890e4248353fa0220555ee02c810d85
Author: bitnukl <bitnukl@users.noreply.github.com>
Date:   Sun Jul 17 20:30:42 2016 +0200

    fixing crash if contact_advisor is left empty

:040000 040000 b82d8200eca677fc86c89dcafcb7cfeedd70328c 01819813e1c0f909b6a016c4b48fe2ef6792b2b0 M  gluon08-repo-patches

```

**Comment by RubenKelevra** [comment]
Das macht irgendwie keinen Sinn.

**Comment by bitnukl** [comment]
fixed
