### ISSUE TITLE
typo im Label vom E-Mail-Adressenfeld

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#60]
"Gib hier eine gültige E-Mail-Adresse an, wo wir dich erreichen können."

Sollte denke ich zu dem werden:

"Gib hier eine gültige E-Mail-Adresse an, über die wir dich erreichen können."

**Comment by bitnukl** [comment]
"Gib hier eine gültige E-Mail-Adresse an, unter der wir dich erreichen können." ?!?

**Comment by bitnukl** [comment]
fixed: https://github.com/VfN-NRW/gluon-firmware-builder/commit/c18e4b9a1ee58acc50953729e0939b2f3d2b2af9
