### ISSUE TITLE
Prüfen ob im Master noch auftritt: "Location address" 

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#61]
Die Übersetzung für die Location address wird nicht gezogen, das ist das Feld für die Anschrift

**Comment by bitnukl** [comment]
Übersetzung neu hinzugefügt: https://github.com/VfN-NRW/gluon-firmware-builder/commit/e9af72bea991b3d20cc8679e4ae1516e8a89d54c
