### ISSUE TITLE
Prüfen ob im Master noch auftritt: "Update Hinweis auf Englisch"

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#62]
`This node will automatically update it's firmware when a new version is available.` Kommt anstatt ein deutscher Hinweis

**Comment by bitnukl** [comment]
gluon-config-mode:reboot wird aktuell gar nicht angezeigt!
(zumindest beim zweiten mal einrichten, evtl. macht das ein Unterscheid.

**Comment by bitnukl** [comment]
fixed
