### ISSUE TITLE
Doppeltes "Willkommen auf der Config-Seite"

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#63]
> Willkommen!
> 
> Willkommen im Konfigurationsmodus für deinen neuen Remscheider Freifunk-Knoten. Bitte fülle das folgende Formular aus um die Einrichtung abzuschließen.

Hier sollte eher sowas stehen wie:

> Willkommen!
> 
> Dies ist der Konfigurationsmodus für deinen neuen Remscheider Freifunk-Knoten. Bitte fülle das folgende Formular aus um die Einrichtung abzuschließen.

**Comment by bitnukl** [comment]
fixed
