### ISSUE TITLE
gigabit geräte haben auf dem WAN immer eine random MAC

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#7]
_From @bitnukl on July 17, 2016 20:41_

Evtl. löst ein revert von https://github.com/VfN-NRW/gluon/commit/3c830dd73ce8456a421b4b61c59522a6afea20af das Problem?

_Copied from original issue: VfN-NRW/gluon#114_

**Comment by bitnukl** [comment]
fixed
