### ISSUE TITLE
Power LED fix on 841N v11 funktioniert nicht

### ISSUE THREAD

**Issue by bitnukl** [VfN-NRW/gluon-firmware-builder#71]

**Comment by RubenKelevra** [comment]
patch needs to be backported https://github.com/VfN-NRW/gluon-firmware-builder/blob/tl-wr841n-v11-power-led-fix/gluon08-patches/openwrt/0058-TL-WR841N-v11-LEDs-use-separate-machine.patch

**Comment by RubenKelevra** [comment]
Patch does not work, router was dead as beef.

We wait for upstream support or wait for integrated support in gluon09.
