### ISSUE TITLE
deutsche reboot message fehlt nach ersteinrichtung

### ISSUE THREAD

**Issue by bitnukl** [VfN-NRW/gluon-firmware-builder#84]
(mal wieder)

**Comment by RubenKelevra** [comment]
4.2a1.6_07 ist kaputt

**Comment by RubenKelevra** [comment]
4.2a1.6_04 ist kaputt

**Comment by RubenKelevra** [comment]
4.2a1.6_02 ist kaputt

**Comment by RubenKelevra** [comment]
Tja, dein approach muss es jetzt retten, ich bin durch mit bisecten

**Comment by bitnukl** [comment]
Vermutlich war es einfach die Größe des Textes. :(
Ein Absatz entfernt, jetzt geht es.

**Comment by bitnukl** [comment]
fixed
