### ISSUE TITLE
In Statistiken einbauen: Routermodell übertragen

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#86]

**Comment by bitnukl** [comment]
Das ist eine sehr gute Idee!

**Comment by RubenKelevra** [comment]
https://github.com/VfN-NRW/gluon-firmware-builder/commit/f1bf20dd42c11a931f14b2da706403e6b11fcfa2

**Comment by RubenKelevra** [comment]
getestet, gelöst
