### ISSUE TITLE
autoupdater: lockfile removal does not seem to work

### ISSUE THREAD

**Issue by RubenKelevra** [VfN-NRW/gluon-firmware-builder#99]
Invalid image checksum!
Starting gluon-radvd...
85remove_lockfile: applet not found
Starting cron...
Starting haveged...

**Comment by bitnukl** [comment]
lockfile nicht mehr da nach erfolgreichem und abgebrochenem update

**Comment by RubenKelevra** [comment]
Wunderbar! :)
